# -*- coding: utf-8 -*-
"""Radius.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YqWhsr1yIRHxzyKKCLy-9LSpC8BA-2w3
"""

import math

radius = float(input("Enter the radius of the circle: "))

# Calculate the area of the circle
area = math.pi * radius ** 2

# Print the result
print(f"The area of the circle with radius {radius} is: {area}")